config/routes.rb
Lifecam::Application.routes.draw do
  resources :roles

  devise_for :models

  devise_for :users

 
  resources :pages

  root :to => 'models#index'
  resources :models 
   resources :messages

end

app/views/structure/_filter.html.erb
<nav>
   <h2 class="left">Наши девушки</h2>
   <div class="menu right">
      <ul>
         <li class="active">ВСЕ</li>
         <li><a href="">Брюнетки</a></li>
         <li><a href="">Блондинки</a></li>
         <li><a href="">Рыжие</a></li>
         <li><a href="">Большой бюст</a></li>
         <li><a href="">Взрослые</a></li>
         <li><a href="">Неформалки</a></li>
      </ul>
   </div>
   <span class="tide"></span>
</nav>

app/views/structure/_footer.html.erb
<div class="footer">
   <div class="bottom-nav">
      <ul>
         <li><a href="">Приватность</a></li>
         <li><a href="">Соглашение</a></li>
         <li><a href="">О компании</a></li>
         <li><a href="">Антиспам</a></li>
         <li><a href="">Ограничения</a></li>
         <li><a href="">Обратная связь</a></li>
         <li><a href="">Помощь</a></li>
         <li><a href="">Оплата</a></li>
         <li><a href="">Бонусы</a></li>
      </ul>
   </div>
   <div class="confine">
      <a href="/">Возрастные ограничения для моделей</a>
   </div>
   <div class="credits">
      <%= link_to image_tag('/images/logo-bttm.png'), "/#{I18n.locale}/", :class => 'logo' %>
      <div>
         <p><%= link_to 'lifecam.cz', "/#{I18n.locale}/" %> &copy; 2012</p>
         <p class="rights">Все права защищены</p>
      </div>
   </div>
   <div class="social">
      <a href="" class="vk"></a>
      <a href="" class="facebook"></a>
      <a href="" class="twitter"></a>
   </div>
   <span class="tide"></span>
</div>

app/views/structure/_header.html.erb
<div class="head">
   <div class="logo">
      <h1><%= link_to '', "/#{I18n.locale}/" %></h1>
   </div>
   <div class="lang-change">
      <ul>
         <li>
            <a href="">CZ</a>
         </li>
         <li class="active">RU</li>
         <li>
            <a href="">EN</a>
         </li>
      </ul>
   </div>
   <div class="head-menu">
      <ul>
         <li><a href="/">онлайн</a></li>
         <li><a href="/">топ</a></li>
         <li><a href="/">все</a></li>
      </ul>
   </div>
   <div class="head-menu">
      <ul>
         <li><a href="/">видео</a></li>
         <li><a href="/">блог</a></li>
      </ul>
      <a href="/" class="help">Помощь</a>
   </div>
   <div class="search-enter-box">
      <div class="entrance">
         <a href="" class="enter">ВХОД</a>
         <a href="" class="men-enter">Мужчинам</a>
         <a href="" class="girl-enter">Девушкам</a>
      </div>
      <div class="search" id="search">
         <%= form_tag models_path, :method => :get do %>
               <%= search_field_tag :name, params[:name] %>
               <%= submit_tag t('search'), :name => nil %>
         <% end %>
         <span class="tide"></span>
      </div>
   </div>
   <span class="tide"></span>
</div>